### ISSUE TITLE
Please consider adding PCEImage Editor

### ISSUE THREAD

**Issue by memalign** [bryanbraun/lets-get-creative#10]
- Tool name: PCEImage Editor

- Short Description: Make pixel art with ASCII. Bring it to life with a playful wobble.

- Link: https://memalign.github.io/m/pceimage/index.html

- Image attached

![download](https://github.com/bryanbraun/lets-get-creative/assets/1755820/2967113f-6bb3-4b69-a78d-2b4a07ef8adc)

**Comment by memalign** [comment]
(Here’s the URL for the ASCII art I used to make the attached image:

https://memalign.github.io/m/pceimage/index.html?w=1&s=10&t=.:#00000000%0Ao:#FFFFFF%0A@:#D5D6AE%0A#:#624073%0A-:#C28CB0%0Ax:#F0DCA9%0A%0A..................................................................................%0A..........@@............@@...........................@@............@@.............%0A.@@.......@@............@@........@@........@@.......@@............@@........@@...%0A.@@...............................@@........@@...............................@@...%0A.....#####..................#####...............#####..................#####......%0A....#######................#######.............#######................#######.....%0A.@.##o###o##..@...........##o###o##.........@.##o###o##..@...........##o###o##....%0A...###---###..............###---###..@........###---###..............###---###..@.%0A...#########...........@..#########...........#########...........@..#########....%0A...###x#x###..............###x#x###...........###x#x###..............###x#x###....%0A...####x####..............####x####...........####x####..............####x####....%0A....##x#x##................##x#x##.............##x#x##................##x#x##.....%0A.....#####..................#####...............#####..................#####......%0A..@.........@............@.........@.........@.........@............@.........@...%0A..@@.........@@........@@.........@@.........@@.........@@........@@.........@@...%0A.............@@........@@...............................@@........@@..............%0A..................................................................................
)

**Comment by bryanbraun** [comment]
This looks great @memalign, and thanks @kunal-arya, for putting together a PR. Gonna merge this now. 🚀
